### ISSUE TITLE
Node 12 and set-output are being deprecated

### ISSUE THREAD

**Issue by kylegwalsh** [shioyang/check-pr-labels-on-push-action#23]
I've noticed the following warnings in GitHub actions when using this action:

```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: shioyang/check-pr-labels-on-push-action, shioyang/check-pr-labels-on-push-action, shioyang/check-pr-labels-on-push-action
```

```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

**Comment by shioyang** [comment]
@kylegwalsh Thank you for the report. [The latest release](https://github.com/shioyang/check-pr-labels-on-push-action/releases/tag/v1.0.7) should fix the warnings.
Please use the latest version.

**Comment by kylegwalsh** [comment]
@shioyang Thanks for the update!

I just tried the fix in my own pipeline and see that the Node.js 12 actions warning has disappeared.

However, I still notice the `set-output` warning. Is the latest release leveraging $GITHUB_STATE or $GITHUB_OUTPUT now?

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
